/**
 * Score page: local, offline PCE scoring against the visitor's own
 * enrolled fingerprint (K), entirely client-side via the `genesis-prnu`
 * Rust scoring core compiled to WASM (`rust/genesis-prnu-wasm`).
 *
 * Hard invariant (docs/security.md, "Where K lives";
 * docs/wasm-scoring-plan.md Phase 5): K never leaves this machine. This
 * file makes no network request of any kind involving the K bytes or the
 * photo bytes -- both are read straight off the `File` objects the user
 * picked and handed to the WASM module in memory. The only network
 * activity on this page at all is the browser's own initial fetch of this
 * page's static JS/WASM assets (the code, not the data), which happens
 * before either file is even chosen.
 *
 * K bytes are kept in a page-lifetime in-memory variable, not written to
 * IndexedDB. That was a deliberate scope cut for this session (the plan
 * allowed either) -- an in-memory-only Uint8Array satisfies "never
 * transmitted, never persisted beyond this tab" with much less code than
 * wiring up IndexedDB, at the cost of having to re-pick the K file after a
 * reload. If cross-session persistence turns out to matter, swap the
 * `kBytes` variable below for an IndexedDB read/write -- nothing else on
 * this page needs to change.
 */

// wasm-pack's `--target web` output: an ES module with a default `init()`
// that fetches and instantiates the .wasm binary, plus the bound exports.
// Generated by `npm run wasm` (this package's `predev`/`prebuild` script)
// from `rust/genesis-prnu-wasm` -- see score/README.md. Not committed
// (score/src/wasm/.gitignore, written by wasm-pack itself).
import init, { score, pceThreshold } from "./wasm/genesis_prnu_wasm.js";

const kInput = document.querySelector<HTMLInputElement>("#kfile")!;
const photoInput = document.querySelector<HTMLInputElement>("#photo")!;
const scoreBtn = document.querySelector<HTMLButtonElement>("#score-btn")!;
const kStatus = document.querySelector<HTMLParagraphElement>("#k-status")!;
const result = document.querySelector<HTMLElement>("#result")!;

let kBytes: Uint8Array | null = null;
let wasmReady: Promise<unknown> | null = null;

function ensureWasm(): Promise<unknown> {
  // Loads and instantiates the WASM module once per page load, lazily
  // (only once the visitor actually starts using the page), and caches
  // the in-flight promise so a fast double-click doesn't double-init.
  if (!wasmReady) wasmReady = init();
  return wasmReady;
}

function updateScoreButton() {
  scoreBtn.disabled = !(kBytes && photoInput.files && photoInput.files.length > 0);
}

kInput.addEventListener("change", async () => {
  const file = kInput.files?.[0];
  if (!file) {
    kBytes = null;
    kStatus.textContent = "";
    updateScoreButton();
    return;
  }
  const buf = await file.arrayBuffer();
  kBytes = new Uint8Array(buf);
  kStatus.textContent = `Loaded ${file.name} (${(file.size / 1024).toFixed(0)} KB) -- kept in this tab's memory only.`;
  kStatus.classList.add("k-hint");
  updateScoreButton();
});

photoInput.addEventListener("change", updateScoreButton);

scoreBtn.addEventListener("click", async () => {
  if (!kBytes) return;
  const photoFile = photoInput.files?.[0];
  if (!photoFile) return;

  result.hidden = false;
  result.className = "working";
  result.innerHTML = "<h2>Scoring…</h2><p>Decoding and correlating locally, no network involved.</p>";

  try {
    await ensureWasm();
    const photoBytes = new Uint8Array(await photoFile.arrayBuffer());
    const pce = score(photoBytes, kBytes);
    const threshold = pceThreshold();
    const passed = pce >= threshold;

    result.className = passed ? "pass" : "fail";
    result.innerHTML = `
      <h2>${passed ? "Matches your fingerprint" : "Does not clear the threshold"}</h2>
      <dl>
        <div class="row"><dt>PCE</dt><dd>${pce.toFixed(1)}</dd></div>
        <div class="row"><dt>Threshold</dt><dd>${threshold.toFixed(1)}</dd></div>
      </dl>
      <p class="caveat">
        This is a local measurement, not a verdict you can show someone
        else -- it is not signed, not on chain, and forgeable by anyone who
        also has this K file. Only a registration on the
        <a href="../verify/">Verify</a> page carries any weight to a third
        party.
      </p>`;
  } catch (err) {
    result.className = "error";
    const message = err instanceof Error ? err.message : String(err);
    result.innerHTML = `<h2>Could not score that</h2><p>${escapeHtml(message)}</p>`;
  }
});

function escapeHtml(s: string): string {
  const div = document.createElement("div");
  div.textContent = s;
  return div.innerHTML;
}
